// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usersgrpc.proto

package usersgrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	UserID               string         `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Username             string         `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Mmr                  int32          `protobuf:"varint,3,opt,name=mmr,proto3" json:"mmr,omitempty"`
	Level                int32          `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Goals                int32          `protobuf:"varint,5,opt,name=goals,proto3" json:"goals,omitempty"`
	TopGoalSpeed         int32          `protobuf:"varint,6,opt,name=topGoalSpeed,proto3" json:"topGoalSpeed,omitempty"`
	Achievements         []string       `protobuf:"bytes,7,rep,name=achievements,proto3" json:"achievements,omitempty"`
	PrivateData          *PrivateData   `protobuf:"bytes,8,opt,name=privateData,proto3" json:"privateData,omitempty"`
	ProtectedData        *ProtectedData `protobuf:"bytes,9,opt,name=protectedData,proto3" json:"protectedData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_4609976ae134140c, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetMmr() int32 {
	if m != nil {
		return m.Mmr
	}
	return 0
}

func (m *User) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *User) GetGoals() int32 {
	if m != nil {
		return m.Goals
	}
	return 0
}

func (m *User) GetTopGoalSpeed() int32 {
	if m != nil {
		return m.TopGoalSpeed
	}
	return 0
}

func (m *User) GetAchievements() []string {
	if m != nil {
		return m.Achievements
	}
	return nil
}

func (m *User) GetPrivateData() *PrivateData {
	if m != nil {
		return m.PrivateData
	}
	return nil
}

func (m *User) GetProtectedData() *ProtectedData {
	if m != nil {
		return m.ProtectedData
	}
	return nil
}

type PrivateData struct {
	Firstname              string   `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname               string   `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email                  string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Created                string   `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	CardID                 string   `protobuf:"bytes,5,opt,name=cardID,proto3" json:"cardID,omitempty"`
	CardExpiryDate         string   `protobuf:"bytes,6,opt,name=cardExpiryDate,proto3" json:"cardExpiryDate,omitempty"`
	CardPIN                string   `protobuf:"bytes,7,opt,name=cardPIN,proto3" json:"cardPIN,omitempty"`
	CreditCardType         string   `protobuf:"bytes,8,opt,name=creditCardType,proto3" json:"creditCardType,omitempty"`
	CreditCardNumber       string   `protobuf:"bytes,9,opt,name=creditCardNumber,proto3" json:"creditCardNumber,omitempty"`
	CreditCardExpiryDate   string   `protobuf:"bytes,10,opt,name=creditCardExpiryDate,proto3" json:"creditCardExpiryDate,omitempty"`
	CreditCardSecurityCode string   `protobuf:"bytes,11,opt,name=creditCardSecurityCode,proto3" json:"creditCardSecurityCode,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *PrivateData) Reset()         { *m = PrivateData{} }
func (m *PrivateData) String() string { return proto.CompactTextString(m) }
func (*PrivateData) ProtoMessage()    {}
func (*PrivateData) Descriptor() ([]byte, []int) {
	return fileDescriptor_4609976ae134140c, []int{1}
}

func (m *PrivateData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivateData.Unmarshal(m, b)
}
func (m *PrivateData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivateData.Marshal(b, m, deterministic)
}
func (m *PrivateData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivateData.Merge(m, src)
}
func (m *PrivateData) XXX_Size() int {
	return xxx_messageInfo_PrivateData.Size(m)
}
func (m *PrivateData) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivateData.DiscardUnknown(m)
}

var xxx_messageInfo_PrivateData proto.InternalMessageInfo

func (m *PrivateData) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *PrivateData) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *PrivateData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *PrivateData) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *PrivateData) GetCardID() string {
	if m != nil {
		return m.CardID
	}
	return ""
}

func (m *PrivateData) GetCardExpiryDate() string {
	if m != nil {
		return m.CardExpiryDate
	}
	return ""
}

func (m *PrivateData) GetCardPIN() string {
	if m != nil {
		return m.CardPIN
	}
	return ""
}

func (m *PrivateData) GetCreditCardType() string {
	if m != nil {
		return m.CreditCardType
	}
	return ""
}

func (m *PrivateData) GetCreditCardNumber() string {
	if m != nil {
		return m.CreditCardNumber
	}
	return ""
}

func (m *PrivateData) GetCreditCardExpiryDate() string {
	if m != nil {
		return m.CreditCardExpiryDate
	}
	return ""
}

func (m *PrivateData) GetCreditCardSecurityCode() string {
	if m != nil {
		return m.CreditCardSecurityCode
	}
	return ""
}

type ProtectedData struct {
	Color                string   `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	AvatarURL            string   `protobuf:"bytes,2,opt,name=avatarURL,proto3" json:"avatarURL,omitempty"`
	UserType             string   `protobuf:"bytes,3,opt,name=userType,proto3" json:"userType,omitempty"`
	City                 string   `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Country              string   `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	Birthday             string   `protobuf:"bytes,6,opt,name=birthday,proto3" json:"birthday,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtectedData) Reset()         { *m = ProtectedData{} }
func (m *ProtectedData) String() string { return proto.CompactTextString(m) }
func (*ProtectedData) ProtoMessage()    {}
func (*ProtectedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_4609976ae134140c, []int{2}
}

func (m *ProtectedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtectedData.Unmarshal(m, b)
}
func (m *ProtectedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtectedData.Marshal(b, m, deterministic)
}
func (m *ProtectedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtectedData.Merge(m, src)
}
func (m *ProtectedData) XXX_Size() int {
	return xxx_messageInfo_ProtectedData.Size(m)
}
func (m *ProtectedData) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtectedData.DiscardUnknown(m)
}

var xxx_messageInfo_ProtectedData proto.InternalMessageInfo

func (m *ProtectedData) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *ProtectedData) GetAvatarURL() string {
	if m != nil {
		return m.AvatarURL
	}
	return ""
}

func (m *ProtectedData) GetUserType() string {
	if m != nil {
		return m.UserType
	}
	return ""
}

func (m *ProtectedData) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *ProtectedData) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *ProtectedData) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

type UsersReply struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersReply) Reset()         { *m = UsersReply{} }
func (m *UsersReply) String() string { return proto.CompactTextString(m) }
func (*UsersReply) ProtoMessage()    {}
func (*UsersReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4609976ae134140c, []int{3}
}

func (m *UsersReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersReply.Unmarshal(m, b)
}
func (m *UsersReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersReply.Marshal(b, m, deterministic)
}
func (m *UsersReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersReply.Merge(m, src)
}
func (m *UsersReply) XXX_Size() int {
	return xxx_messageInfo_UsersReply.Size(m)
}
func (m *UsersReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersReply.DiscardUnknown(m)
}

var xxx_messageInfo_UsersReply proto.InternalMessageInfo

func (m *UsersReply) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type UsersRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersRequest) Reset()         { *m = UsersRequest{} }
func (m *UsersRequest) String() string { return proto.CompactTextString(m) }
func (*UsersRequest) ProtoMessage()    {}
func (*UsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4609976ae134140c, []int{4}
}

func (m *UsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersRequest.Unmarshal(m, b)
}
func (m *UsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersRequest.Marshal(b, m, deterministic)
}
func (m *UsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersRequest.Merge(m, src)
}
func (m *UsersRequest) XXX_Size() int {
	return xxx_messageInfo_UsersRequest.Size(m)
}
func (m *UsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsersRequest proto.InternalMessageInfo

func (m *UsersRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "usersgrpc.User")
	proto.RegisterType((*PrivateData)(nil), "usersgrpc.PrivateData")
	proto.RegisterType((*ProtectedData)(nil), "usersgrpc.ProtectedData")
	proto.RegisterType((*UsersReply)(nil), "usersgrpc.UsersReply")
	proto.RegisterType((*UsersRequest)(nil), "usersgrpc.UsersRequest")
}

func init() { proto.RegisterFile("usersgrpc.proto", fileDescriptor_4609976ae134140c) }

var fileDescriptor_4609976ae134140c = []byte{
	// 555 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x4b, 0x6e, 0xdb, 0x30,
	0x10, 0x86, 0xab, 0xf8, 0xa9, 0x71, 0xd2, 0x04, 0x44, 0xea, 0x12, 0x46, 0x17, 0x86, 0x16, 0x81,
	0xd1, 0x45, 0x16, 0x2e, 0x10, 0x74, 0x95, 0x8d, 0x5d, 0x14, 0x06, 0x8a, 0x20, 0xa0, 0xeb, 0x03,
	0xd0, 0xe2, 0x34, 0x11, 0x20, 0x59, 0x2a, 0x45, 0x1b, 0xd5, 0x31, 0x7a, 0x8c, 0x5e, 0xa1, 0x07,
	0xeb, 0xba, 0xe0, 0x88, 0xb6, 0x24, 0xa7, 0x5e, 0x74, 0xc7, 0xff, 0x9b, 0x87, 0xc8, 0x7f, 0x48,
	0xc1, 0xe5, 0x36, 0x47, 0x9d, 0x3f, 0xe9, 0x2c, 0xbc, 0xcd, 0x74, 0x6a, 0x52, 0xe6, 0x1f, 0x40,
	0xf0, 0xfb, 0x0c, 0xda, 0xab, 0x1c, 0x35, 0x1b, 0x42, 0xd7, 0xd2, 0xc5, 0x9c, 0x7b, 0x63, 0x6f,
	0xe2, 0x0b, 0xa7, 0xd8, 0x08, 0xfa, 0x76, 0xb5, 0x91, 0x09, 0xf2, 0x33, 0x8a, 0x1c, 0x34, 0xbb,
	0x82, 0x56, 0x92, 0x68, 0xde, 0x1a, 0x7b, 0x93, 0x8e, 0xb0, 0x4b, 0x76, 0x0d, 0x9d, 0x18, 0x77,
	0x18, 0xf3, 0x36, 0xb1, 0x52, 0x58, 0xfa, 0x94, 0xca, 0x38, 0xe7, 0x9d, 0x92, 0x92, 0x60, 0x01,
	0x9c, 0x9b, 0x34, 0xfb, 0x9c, 0xca, 0x78, 0x99, 0x21, 0x2a, 0xde, 0xa5, 0x60, 0x83, 0xd9, 0x1c,
	0x19, 0x3e, 0x47, 0xb8, 0xc3, 0x04, 0x37, 0x26, 0xe7, 0xbd, 0x71, 0x6b, 0xe2, 0x8b, 0x06, 0x63,
	0x1f, 0x61, 0x90, 0xe9, 0x68, 0x27, 0x0d, 0xce, 0xa5, 0x91, 0xbc, 0x3f, 0xf6, 0x26, 0x83, 0xe9,
	0xf0, 0xb6, 0x3a, 0xf4, 0x63, 0x15, 0x15, 0xf5, 0x54, 0x76, 0x0f, 0x17, 0xd6, 0x10, 0x0c, 0x0d,
	0x2a, 0xaa, 0xf5, 0xa9, 0x96, 0x37, 0x6a, 0x6b, 0x71, 0xd1, 0x4c, 0x0f, 0x7e, 0xb6, 0x60, 0x50,
	0x6b, 0xce, 0xde, 0x81, 0xff, 0x2d, 0xd2, 0xb9, 0x21, 0xb3, 0x4a, 0x1b, 0x2b, 0x60, 0x9d, 0x8c,
	0xa5, 0x0b, 0x3a, 0x27, 0xf7, 0xda, 0x3a, 0x84, 0x89, 0x8c, 0x62, 0xf2, 0xd2, 0x17, 0xa5, 0x60,
	0x1c, 0x7a, 0xa1, 0x46, 0x69, 0x50, 0x91, 0x9f, 0xbe, 0xd8, 0x4b, 0x3b, 0xad, 0x50, 0x6a, 0xb5,
	0x98, 0x93, 0xa5, 0xbe, 0x70, 0x8a, 0xdd, 0xc0, 0x6b, 0xbb, 0xfa, 0xf4, 0x23, 0x8b, 0x74, 0x31,
	0x97, 0x06, 0xc9, 0x55, 0x5f, 0x1c, 0x51, 0xea, 0x2c, 0xb5, 0x7a, 0x5c, 0x3c, 0xf0, 0x9e, 0xeb,
	0x5c, 0x4a, 0xea, 0xa0, 0x51, 0x45, 0x66, 0x26, 0xb5, 0xfa, 0x5a, 0x64, 0x48, 0x86, 0xda, 0x0e,
	0x0d, 0xca, 0xde, 0xc3, 0x55, 0x45, 0x1e, 0xb6, 0xc9, 0x1a, 0x35, 0xd9, 0xe7, 0x8b, 0x17, 0x9c,
	0x4d, 0xe1, 0xba, 0x62, 0xb5, 0xbd, 0x01, 0xe5, 0xff, 0x33, 0xc6, 0xee, 0x60, 0x58, 0xf1, 0x25,
	0x86, 0x5b, 0x1d, 0x99, 0x62, 0x96, 0x2a, 0xe4, 0x03, 0xaa, 0x3a, 0x11, 0x0d, 0x7e, 0x79, 0x70,
	0xd1, 0x18, 0x9a, 0xf5, 0x36, 0x4c, 0xe3, 0x54, 0xbb, 0x89, 0x94, 0xc2, 0xce, 0x4a, 0xee, 0xa4,
	0x91, 0x7a, 0x25, 0xbe, 0xb8, 0x71, 0x54, 0x60, 0x7f, 0xeb, 0xe9, 0xfc, 0xad, 0xea, 0xd6, 0xd3,
	0xc9, 0x19, 0xb4, 0xc3, 0xc8, 0x14, 0x6e, 0x24, 0xb4, 0x26, 0x3f, 0xd3, 0xed, 0xc6, 0xe8, 0xc2,
	0x0d, 0x64, 0x2f, 0x6d, 0xa7, 0x75, 0xa4, 0xcd, 0xb3, 0x92, 0x85, 0x9b, 0xc5, 0x41, 0x07, 0x63,
	0x00, 0xfb, 0xf6, 0x72, 0x81, 0x59, 0x5c, 0x50, 0x5f, 0x7b, 0x3e, 0x8f, 0xde, 0x01, 0xad, 0x83,
	0x1b, 0x38, 0x77, 0x19, 0xdf, 0xb7, 0x98, 0x9b, 0x53, 0xaf, 0x74, 0xfa, 0xc7, 0x73, 0x89, 0x4b,
	0xd4, 0xbb, 0x28, 0xb4, 0xf6, 0xc1, 0x8c, 0xee, 0x0a, 0x3d, 0xee, 0xcb, 0xda, 0x8d, 0xb6, 0x60,
	0xf4, 0xe6, 0x08, 0x94, 0x5b, 0x08, 0x5e, 0xb1, 0x3b, 0xe8, 0x0b, 0x94, 0x8a, 0xaa, 0xde, 0xbe,
	0x4c, 0xa2, 0x5d, 0x8c, 0x8e, 0xdb, 0x51, 0x1d, 0xac, 0x32, 0xf5, 0xff, 0xdf, 0xbb, 0x07, 0x98,
	0x63, 0x8c, 0xae, 0xee, 0xe4, 0x17, 0x4f, 0xd5, 0xaf, 0xbb, 0xf4, 0x47, 0xfb, 0xf0, 0x37, 0x00,
	0x00, 0xff, 0xff, 0x19, 0x30, 0xaf, 0x74, 0xe4, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersServiceClient is the client API for UsersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersServiceClient interface {
	CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*UsersReply, error)
	ReadUser(ctx context.Context, in *UsersRequest, opts ...grpc.CallOption) (*User, error)
	UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*UsersReply, error)
	DeleteUser(ctx context.Context, in *UsersRequest, opts ...grpc.CallOption) (*UsersReply, error)
}

type usersServiceClient struct {
	cc *grpc.ClientConn
}

func NewUsersServiceClient(cc *grpc.ClientConn) UsersServiceClient {
	return &usersServiceClient{cc}
}

func (c *usersServiceClient) CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*UsersReply, error) {
	out := new(UsersReply)
	err := c.cc.Invoke(ctx, "/usersgrpc.UsersService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) ReadUser(ctx context.Context, in *UsersRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/usersgrpc.UsersService/ReadUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*UsersReply, error) {
	out := new(UsersReply)
	err := c.cc.Invoke(ctx, "/usersgrpc.UsersService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) DeleteUser(ctx context.Context, in *UsersRequest, opts ...grpc.CallOption) (*UsersReply, error) {
	out := new(UsersReply)
	err := c.cc.Invoke(ctx, "/usersgrpc.UsersService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServiceServer is the server API for UsersService service.
type UsersServiceServer interface {
	CreateUser(context.Context, *User) (*UsersReply, error)
	ReadUser(context.Context, *UsersRequest) (*User, error)
	UpdateUser(context.Context, *User) (*UsersReply, error)
	DeleteUser(context.Context, *UsersRequest) (*UsersReply, error)
}

// UnimplementedUsersServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUsersServiceServer struct {
}

func (*UnimplementedUsersServiceServer) CreateUser(ctx context.Context, req *User) (*UsersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUsersServiceServer) ReadUser(ctx context.Context, req *UsersRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadUser not implemented")
}
func (*UnimplementedUsersServiceServer) UpdateUser(ctx context.Context, req *User) (*UsersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedUsersServiceServer) DeleteUser(ctx context.Context, req *UsersRequest) (*UsersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}

func RegisterUsersServiceServer(s *grpc.Server, srv UsersServiceServer) {
	s.RegisterService(&_UsersService_serviceDesc, srv)
}

func _UsersService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersgrpc.UsersService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).CreateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_ReadUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).ReadUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersgrpc.UsersService/ReadUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).ReadUser(ctx, req.(*UsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersgrpc.UsersService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).UpdateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usersgrpc.UsersService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).DeleteUser(ctx, req.(*UsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UsersService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "usersgrpc.UsersService",
	HandlerType: (*UsersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UsersService_CreateUser_Handler,
		},
		{
			MethodName: "ReadUser",
			Handler:    _UsersService_ReadUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UsersService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UsersService_DeleteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "usersgrpc.proto",
}
