version: '3'
services:
  users-service:
    container_name: 'users-service'
    build: './'
    volumes:
      - './api:$HOME/go/src/github.com/iafoosball/users-service'
#      /cmd/iafoosball-server
    depends_on:
      - 'arangodb'
  arangodb:
    container_name: 'users-arangodb'
    image: arangodb/arangodb:3.3.11
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=joe
    volumes:
      - /tmp/arangodb:/var/lib/arangodb3
#      - ./initArango:/usr/local/bin/initArango
    # command:
    #   bash -c "/usr/local/bin/initArango"