version: '2'
services:
  users-service:
    build: './'
    ports:
      - 9005:9005
    depends_on:
      - arangodb  
    links:
      - arangodb:arangodb
  arangodb:
    container_name: users-arangodb
    image: arangodb/arangodb:latest
    ports:
      - 9006:8529
    environment:
      - ARANGO_ROOT_PASSWORD=iafoosball@users for the win
    volumes:
      - var/lib/iafoosball/arango/user-data:/var/lib/arangodb3

networks: 
  default:
    external:
      name: kong_iafoosball