version: '2'
services:
  users-service:
    container_name: users-service
    build: './'
    ports:
      - 9005:4444
    depends_on:
      - arangodb  
    links:
      - arangodb:arangodb
  arangodb:
    container_name: users-arangodb
    image: arangodb/arangodb:latest
    ports:
      - 9006:8529
    environment:
      - ARANGO_ROOT_PASSWORD=users-password
      - REDIS_ADDR=redis:6379
    volumes:
      - $HOME/iafoosball/stag/arango/user-data:/var/lib/arangodb3

networks: 
  default:
    external:
      name: kong_iafoosball