version: '3'
services:
  users-service:
    container_name: users-service
    build: './'
    ports:
      - "8020:8020/tcp"
    depends_on:
      - arangodb  
    links:
      - arangodb:arangodb
  arangodb:
    container_name: users-arangodb
    image: arangodb/arangodb:latest
    ports:
      - "8021:8529/tcp"
    environment:
      ARANGO_ROOT_PASSWORD: users-password
    volumes:
      - /var/lib/iafoosball/stag/arango/user-data:/var/lib/arangodb3
networks: 
  default:
    external:
      name: kong_iafoosball