version: '2'
services:
  users:
    container_name: 'users-service'
    build: './'
    ports:
      - 9005:9005
    links:
      - arangodb
    depends_on:
      - arangodb
  arangodb:
    container_name: 'users-arangodb'
    image: arangodb/arangodb:latest
    ports:
      - 9006:9006
    environment:
      - ARANGO_ROOT_PASSWORD=iafoosball@users for the win
    volumes:
      - /var/lib/iafoosball/arango/user-data:/var/lib/arangodb3

networks: 
  default:
    external:
      name: kong_iafoosball