// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userspb.proto

package userspb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Userhash             string   `protobuf:"bytes,1,opt,name=userhash,proto3" json:"userhash,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Mmr                  int32    `protobuf:"varint,3,opt,name=mmr,proto3" json:"mmr,omitempty"`
	Winrate              int32    `protobuf:"varint,4,opt,name=winrate,proto3" json:"winrate,omitempty"`
	Totalgoals           int32    `protobuf:"varint,5,opt,name=totalgoals,proto3" json:"totalgoals,omitempty"`
	Achievements         []string `protobuf:"bytes,6,rep,name=achievements,proto3" json:"achievements,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_04967996b3bbbfbf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserhash() string {
	if m != nil {
		return m.Userhash
	}
	return ""
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetMmr() int32 {
	if m != nil {
		return m.Mmr
	}
	return 0
}

func (m *User) GetWinrate() int32 {
	if m != nil {
		return m.Winrate
	}
	return 0
}

func (m *User) GetTotalgoals() int32 {
	if m != nil {
		return m.Totalgoals
	}
	return 0
}

func (m *User) GetAchievements() []string {
	if m != nil {
		return m.Achievements
	}
	return nil
}

type ReadOneRequest struct {
	Userhash             string   `protobuf:"bytes,1,opt,name=userhash,proto3" json:"userhash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadOneRequest) Reset()         { *m = ReadOneRequest{} }
func (m *ReadOneRequest) String() string { return proto.CompactTextString(m) }
func (*ReadOneRequest) ProtoMessage()    {}
func (*ReadOneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_04967996b3bbbfbf, []int{1}
}

func (m *ReadOneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadOneRequest.Unmarshal(m, b)
}
func (m *ReadOneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadOneRequest.Marshal(b, m, deterministic)
}
func (m *ReadOneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadOneRequest.Merge(m, src)
}
func (m *ReadOneRequest) XXX_Size() int {
	return xxx_messageInfo_ReadOneRequest.Size(m)
}
func (m *ReadOneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadOneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadOneRequest proto.InternalMessageInfo

func (m *ReadOneRequest) GetUserhash() string {
	if m != nil {
		return m.Userhash
	}
	return ""
}

type ReadOneResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadOneResponse) Reset()         { *m = ReadOneResponse{} }
func (m *ReadOneResponse) String() string { return proto.CompactTextString(m) }
func (*ReadOneResponse) ProtoMessage()    {}
func (*ReadOneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_04967996b3bbbfbf, []int{2}
}

func (m *ReadOneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadOneResponse.Unmarshal(m, b)
}
func (m *ReadOneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadOneResponse.Marshal(b, m, deterministic)
}
func (m *ReadOneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadOneResponse.Merge(m, src)
}
func (m *ReadOneResponse) XXX_Size() int {
	return xxx_messageInfo_ReadOneResponse.Size(m)
}
func (m *ReadOneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadOneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadOneResponse proto.InternalMessageInfo

func (m *ReadOneResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "userspb.User")
	proto.RegisterType((*ReadOneRequest)(nil), "userspb.ReadOneRequest")
	proto.RegisterType((*ReadOneResponse)(nil), "userspb.ReadOneResponse")
}

func init() { proto.RegisterFile("userspb.proto", fileDescriptor_04967996b3bbbfbf) }

var fileDescriptor_04967996b3bbbfbf = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0x45, 0x09, 0x49, 0x1b, 0x3a, 0xb4, 0x80, 0x66, 0x83, 0xd5, 0x05, 0x0a, 0x5e, 0x65, 0x81,
	0xba, 0x28, 0xac, 0x39, 0x02, 0x48, 0x46, 0x1c, 0xc0, 0x0d, 0x23, 0x12, 0xd1, 0xd8, 0xc1, 0xe3,
	0x96, 0x5b, 0x71, 0x46, 0x64, 0xb7, 0x89, 0x88, 0x90, 0xd8, 0xe5, 0xfd, 0xf7, 0x15, 0x8f, 0x3e,
	0x2c, 0x76, 0x4c, 0x8e, 0xbb, 0xcd, 0xaa, 0x73, 0xd6, 0x5b, 0xcc, 0x8f, 0x28, 0xbf, 0x13, 0xc8,
	0x5e, 0x99, 0x1c, 0x2e, 0xe1, 0x2c, 0x64, 0xb5, 0xe6, 0x5a, 0x24, 0x45, 0x52, 0xce, 0xd4, 0xc0,
	0xc1, 0x99, 0xa6, 0xfa, 0x30, 0xba, 0x25, 0x71, 0x7a, 0x70, 0x3d, 0xe3, 0x15, 0xa4, 0x6d, 0xeb,
	0x44, 0x5a, 0x24, 0xe5, 0x44, 0x85, 0x4f, 0x14, 0x90, 0x7f, 0x35, 0xc6, 0x69, 0x4f, 0x22, 0x8b,
	0x69, 0x8f, 0x78, 0x03, 0xe0, 0xad, 0xd7, 0xdb, 0x77, 0xab, 0xb7, 0x2c, 0x26, 0x51, 0xfe, 0x4a,
	0x50, 0xc2, 0x5c, 0x57, 0x75, 0x43, 0x7b, 0x6a, 0xc9, 0x78, 0x16, 0xd3, 0x22, 0x2d, 0x67, 0x6a,
	0x94, 0xc9, 0x3b, 0xb8, 0x50, 0xa4, 0xdf, 0x9e, 0x0d, 0x29, 0xfa, 0xdc, 0x11, 0xfb, 0xff, 0x2e,
	0x97, 0x0f, 0x70, 0x39, 0xb4, 0xb9, 0xb3, 0x86, 0x09, 0x6f, 0x21, 0x0b, 0x3a, 0x56, 0xcf, 0xd7,
	0x8b, 0x55, 0x3f, 0x4c, 0x58, 0x41, 0x45, 0xb5, 0x7e, 0x82, 0x79, 0x20, 0x7e, 0x21, 0xb7, 0x6f,
	0x2a, 0xc2, 0x47, 0xc8, 0x8f, 0x7f, 0xc1, 0xeb, 0xa1, 0x3f, 0xbe, 0x62, 0x29, 0xfe, 0x8a, 0xc3,
	0x83, 0xf2, 0x64, 0x33, 0x8d, 0xa3, 0xdf, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x97, 0x8b, 0x41,
	0xb9, 0x85, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersServiceClient is the client API for UsersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersServiceClient interface {
	ReadOne(ctx context.Context, in *ReadOneRequest, opts ...grpc.CallOption) (*ReadOneResponse, error)
}

type usersServiceClient struct {
	cc *grpc.ClientConn
}

func NewUsersServiceClient(cc *grpc.ClientConn) UsersServiceClient {
	return &usersServiceClient{cc}
}

func (c *usersServiceClient) ReadOne(ctx context.Context, in *ReadOneRequest, opts ...grpc.CallOption) (*ReadOneResponse, error) {
	out := new(ReadOneResponse)
	err := c.cc.Invoke(ctx, "/userspb.UsersService/ReadOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServiceServer is the server API for UsersService service.
type UsersServiceServer interface {
	ReadOne(context.Context, *ReadOneRequest) (*ReadOneResponse, error)
}

// UnimplementedUsersServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUsersServiceServer struct {
}

func (*UnimplementedUsersServiceServer) ReadOne(ctx context.Context, req *ReadOneRequest) (*ReadOneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadOne not implemented")
}

func RegisterUsersServiceServer(s *grpc.Server, srv UsersServiceServer) {
	s.RegisterService(&_UsersService_serviceDesc, srv)
}

func _UsersService_ReadOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).ReadOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userspb.UsersService/ReadOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).ReadOne(ctx, req.(*ReadOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UsersService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "userspb.UsersService",
	HandlerType: (*UsersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadOne",
			Handler:    _UsersService_ReadOne_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "userspb.proto",
}
